name: 'Generate release notes'
description: 'Generate release notes'
inputs:
  auth_token:
    description: 'The token used to authenticate to GitHub.'
    required: true
  output:
    description: 'The output file to save the release notes to.'
    required: true
  build_description:
    description: 'Build description.'
    required: true
  prs_to_consider:
    description: 'A comma-separated list of PRs to consider including in the changelog.'
    required: true
  branch_name:
    description: 'The branch to generate release notes for.'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
