version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  target-branch: main
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/independent
  - /eng/dependabot/nuget.org
  schedule:
    interval: daily
  target-branch: main
  ignore:
  - dependency-name: Microsoft.Extensions.*
    update-types:
    - version-update:semver-major
  - dependency-name: Moq
  commit-message:
    prefix: '[main] '
  groups:
    azure-storage-dependencies:
      patterns:
      - Azure.Storage.*
    identity-dependencies:
      patterns:
      - Azure.Identity
      - Microsoft.Identity.*
      - Microsoft.IdentityModel.*
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/net*
  schedule:
    interval: daily
  target-branch: main
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  commit-message:
    prefix: '[main] '
  groups:
    runtime-dependencies:
      patterns:
      - Microsoft.Extensions.*
      - Microsoft.NETCore.App.Runtime.*
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/independent
  - /eng/dependabot/nuget.org
  schedule:
    interval: daily
  target-branch: release/8.0
  ignore:
  - dependency-name: Microsoft.Extensions.*
    update-types:
    - version-update:semver-major
  - dependency-name: Moq
  commit-message:
    prefix: '[release/8.0] '
  groups:
    azure-storage-dependencies:
      patterns:
      - Azure.Storage.*
    identity-dependencies:
      patterns:
      - Azure.Identity
      - Microsoft.Identity.*
      - Microsoft.IdentityModel.*
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/net*
  schedule:
    interval: daily
  target-branch: release/8.0
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  commit-message:
    prefix: '[release/8.0] '
  groups:
    runtime-dependencies:
      patterns:
      - Microsoft.Extensions.*
      - Microsoft.NETCore.App.Runtime.*
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/independent
  - /eng/dependabot/nuget.org
  schedule:
    interval: daily
  target-branch: release/6.x
  ignore:
  - dependency-name: Microsoft.Extensions.*
    update-types:
    - version-update:semver-major
  - dependency-name: Moq
  commit-message:
    prefix: '[release/6.x] '
  groups:
    azure-storage-dependencies:
      patterns:
      - Azure.Storage.*
    identity-dependencies:
      patterns:
      - Azure.Identity
      - Microsoft.Identity.*
      - Microsoft.IdentityModel.*
- package-ecosystem: nuget
  directories:
  - /eng/dependabot/net*
  schedule:
    interval: daily
  target-branch: release/6.x
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  commit-message:
    prefix: '[release/6.x] '
  groups:
    runtime-dependencies:
      patterns:
      - Microsoft.Extensions.*
      - Microsoft.NETCore.App.Runtime.*
