#! Use https://carvel.dev/ytt/ to generate this template.
#! Either use the "Regenerate dependabot.yml" task in Codespaces, or run the following command:
#! > ytt -f .github/dependabot.template.yml > .github/dependabot.yml

#@ def getBranches():
#@   return [
#@     "main",
#@     "release/8.0",
#@     "release/6.x"
#@   ]
#@ end

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
#@ for branch in getBranches():
#@ commit_prefix = "[" + branch + "] "
  - package-ecosystem: "nuget"
    directories:
      - /eng/dependabot/independent
      - /eng/dependabot/nuget.org
    schedule:
      interval: "daily"
    target-branch: #@ branch
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "Moq"
    commit-message:
      prefix: #@ commit_prefix
    groups:
      azure-storage-dependencies:
        patterns:
          - "Azure.Storage.*"
      identity-dependencies:
        patterns:
          - "Azure.Identity"
          - "Microsoft.Identity.*"
          - "Microsoft.IdentityModel.*"
  - package-ecosystem: "nuget"
    directories:
      - /eng/dependabot/net*
    schedule:
      interval: "daily"
    target-branch: #@ branch
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    commit-message:
      prefix: #@ commit_prefix
    groups:
      runtime-dependencies:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.NETCore.App.Runtime.*"
#@ end
