name: 'Submit To Do Issue'

on:
  workflow_run:
    workflows: ["Scan For To Do Comments"]
    types:
      - completed

permissions:
  issues: write

jobs:
  submit-todo-issue:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Test
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.workflow_run);
