name: 'Sync Branch'
description: 'Syncs one branch to another'
inputs:
  branch:
    description: 'The branch to update.'
    required: true
  base_branch:
    description: 'The base branch to sync with.'
    required: true
  auth_token:
    description: 'The token used to authenticate to GitHub.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        persist-credentials: true # We need to persist credentials to push the resulting changes upstream.
        fetch-depth: 0 # Fetch the entire repo for the below git operations
        ref: ${{ inputs.branch }}
    - name: Sync branch
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # Activate the ours merge driver to respect any branch specific files
        git config merge.ours.driver true
        git merge "$base_branch" --strategy=ort --strategy-option=theirs

        matches=$(perl -ne '/^([^\s]+)\s+merge=ours/gm && print "$1 "' .gitattributes)
        for match in $matches; do
            git checkout --no-overlay "$target_branch" -- "$match"
        done
      env:
        target_branch: origin/${{ inputs.branch }}
    - name: Open PR
      uses: ./.github/actions/open-pr
      with:
        files_to_commit: "*"
        title: '[${{ inputs.branch }}] Sync branch with ${{ inputs.base_branch }}'
        commit_message: Restore branch-specific files
        body: Sync branch with ${{ inputs.base_branch }}. This PR was auto generated and will not be automatically merged in.
        branch_name: sync/${{ inputs.branch }}
        fail_if_files_unchanged: false
        always_create_pr: true
        labels: 'automatic-pr'
        auth_token: ${{ inputs.auth_token }}
