name: 'Generate linter diff'
description: 'Generates a diff file meant for consumption by the submit-linter-suggestions workflow.'
inputs:
  output_file:
    description: 'The file to save the diff to.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Open PR
      run: |
        git diff --minimal --unified=0 --no-prefix --text > "$OUTPUT_FILE"
      shell: bash
      env:
        OUTPUT_FILE: ${{ inputs.output_file }}
