name: 'Check markdown links'
on:
  pull_request:
    paths: ['**.md']
    branches: ['main']

permissions:
  pull-requests: read

jobs:
  check-markdown-links:
    name: 'Check markdown links'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/linters/check-markdown-links-config.json
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
