name: "Create release announcement"

on:
  release:
    types: [released]
    

permissions:
  issues: write

jobs:
  create-announcement:
    runs-on: ubuntu-latest

    steps:
      - name: Create or update shipped branch
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          script: |
            console.log(context.payload.release);
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `New Release ${context.payload.release.name}`,
              body: `${context.payload.release.body}\n\n${context.payload.release.html_url}`,
            });
