name: 'C# linting'
on:
  pull_request:
    paths: ['src/**.cs']
    branches: ['main', 'release/6.x', 'release/7.*']

permissions:
  pull-requests: read

jobs:
  lint-csharp:
    name: 'C# Linting'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0

      - name: Get base commit for the PR
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_ENV
          echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"

      - name: Get changed files
        run: |
          echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
          changed_source_files=$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | { grep "**.cs$" || test $? = 1; })
          echo "Files to validate: '${changed_source_files}'"
          echo "updated_files=$(echo ${changed_source_files})" >> $GITHUB_ENV

      - name: Run dotnet restore
        run: ./dotnet.sh restore

      - name: Run dotnet format (whitespace)
        run: ./dotnet.sh format whitespace --no-restore --include ${{ env.updated_files }}

      - name: Run dotnet format (style)
        run: ./dotnet.sh format style --no-restore --include ${{ env.updated_files }}

      - name: Generate artifacts
        run: |
          mkdir -p ./pr
          cp $GITHUB_EVENT_PATH ./pr/pr-event.json
          echo -n $GITHUB_EVENT_NAME > ./pr/pr-event-name
          git diff > ./pr/linter.diff

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pr-linter
          path: pr/
