name: Scan For To Do Comments
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  scan-for-todo-issue:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/TODO')
    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - name: Generate artifacts
        run: |
          trimmed_comment=$(echo "${{ github.event.comment.body }}" | sed 's|/TODO ||I')
          mkdir -p ./issue
          echo -n $trimmed_comment > ./issue/issue-title
          echo -n "${{ github.event.comment.html_url }}" > ./issue/issue-url
          echo -n "${{ github.event.comment.user.login }}" > ./issue/issue-user
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: issue-todo
          path: issue/
