name: 'Submit linter suggestions'

on:
  workflow_run:
    workflows: ["C# linting", "Add Markdown Feedback"]
    types:
      - completed

permissions: {}

jobs:
  submit-linter-suggestions:
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    name: 'Submit linter suggestions'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          persist-credentials: false

      - name: Set C# Linting Env Vars
        if: ${{ github.event.workflow_run.name == 'C# Linting' }}
        run: |
          echo 'reporter_name=dotnet format' >> $GITHUB_ENV
          echo 'workflow_name=lint-csharp.yml' >> $GITHUB_ENV
          echo 'max_suggestions=10' >> $GITHUB_ENV
          echo 'run_local_command=dotnet format style && dotnet format whitespace' >> $GITHUB_ENV

      - name: Set Append Markdown Feedback Env Vars
        if: ${{ github.event.workflow_run.name == 'Add Markdown Feedback' }}
        run: |
          echo 'reporter_name=Add Markdown Feedback' >> $GITHUB_ENV
          echo 'workflow_name=add-markdown-feedback.yml' >> $GITHUB_ENV

      # We need to checkout the repo to use our custom action
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Download the artifact from the workflow that kicked off this one.
      # The default artifact download action doesn't support cross-workflow
      # artifacts, so use a 3rd party one.
      - name: 'Download linting results'
        uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67
        with:
          workflow: ${{env.workflow_name}}
          run_id: ${{github.event.workflow_run.id }}
          name: linter
          path: ${{ github.workspace }}/linter

      - name: Submit formatting suggestions
        uses: ./.github/actions/create-suggestions-from-diff
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          diff_file: ${{ github.workspace }}/linter/linter.diff
          reporter: ${{ env.reporter_name }}
          max_suggestions: ${{ env.max_suggestions }}
          run_local_command: ${{ env.run_local_command }}
