on:
  release:
    types: [released]

permissions:
  contents: write

env:
  shipping_branch_prefix: 'shipping'

jobs:
  update-shipping-branch:
    name: '[${{ GITHUB_REF }}] Update shipping branch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update shipping branch
        run: |
          release_version=${GITHUB_REF#ref/tags/v}
          if [[ ! "$release_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Unexpected release tag: $release_version."
              exit 1
          fi

          major_minor_version=${release_version%.*}
          shipping_branch_name = "${{ env.shipping_branch_prefix }}/$major_minor_version"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push --force --set-upstream origin "HEAD:$shipping_branch_name"
