name: Track shipped versions
on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-shipping-branch:
    name: '[${{ github.ref_name }}] Update shipping branch'
    runs-on: ubuntu-latest

    steps:
      - name: Calculate shipping branch name
        id: calculateBranchName
        run: |
          release_version=${GITHUB_REF_NAME%-*}
          if [[ ! "$release_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Unexpected release tag: $release_version."
              exit 1
          fi

          major_minor_version=${release_version%.*}
          shipping_branch_name="shipped/$major_minor_version"
          echo "shipping_branch_name=refs/head$shipping_branch_name" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v6.4.0
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "${{ steps.calculateBranchName.outputs.shipping_branch_name }}"
              sha: context.sha
            });
